### ISSUE TITLE
编译请添加依赖

### ISSUE THREAD

**Issue by shenyz** [ykxVK8yL5L/luci-app-synology#1]
感谢您的APP
劳烦makefile的依赖加上qemu-img 不然镜像不会生成qcow2镜像
最好把qemu-nbd 也加上

**Comment by ykxVK8yL5L** [comment]
> 感谢您的APP 劳烦makefile的依赖加上qemu-img 不然镜像不会生成qcow2镜像 最好把qemu-nbd 也加上
感谢提醒 抱歉现在才回复

**Comment by ykxVK8yL5L** [comment]
已经添加
